### PR TITLE
Using async style callback for spawn in addUser()

### PR DESCRIPTION
**Pull request by stackptr**
Should make `grant_access_to_last_attempt.js` more predictable!

### CODE REVIEW

**Comment by jerkey** [comment]
the spawn('/usr/local/bin/roroot') has to wait until the completion of fs.appendFileSync, because roroot sets the disk back to read-only mode.

**Comment by stackptr** [comment]
`appendFileSync` should be synchronous (as opposed to `appendFile`)--so the latter `spawn` should happen in the correct order. Does it still not function correctly? I can't really test on my end

**Comment by jerkey** [comment]
ok i tried it.  it did not work!  it does not give an error and says it's adding to the file, but the file does not get changed.  Also, afterwards the filesystem is left in read-write mode (it should be set back to read-only using the roroot tool)

**Comment by stackptr** [comment]
Ok, I think there are two ways to solve this, after reading a little more about `child_process`[1]:

Using `spawn`, the `Stream` event to use in order to know when to initiate the file append would be the `end` event, not `data` -- I think the way it is now, the callback is executed as soon as the mount command _starts_, which means the file write will happen too soon.

Alternatively, you could use `exec` instead of `spawn` since that has a more traditional callback approach involving a buffer:

```shell
child_process.exec('/bin/mount -o remount rw /', function(err, stdout, stderr){
  fs.appendFile(__dirname + '/access_control_list', entry, function(){
    // Use traditional async appendFile callback
    child_process.exec('/usr/local/bin/roroot');
  });
});
```

[1] https://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html

**Pull request merged**
